{% set name = "bytecode" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d41ad53c657ba0bef1cb4828d9d6e450766e31cb66c6f91fc1851f052889d1b7

build:
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - setuptools_scm
    - toml
  run:
    - python
    - typing_extensions  # [py<310]

test:
  requires:
    - pip
  imports:
    - bytecode
  commands:
    - pip check

about:
  home: https://github.com/vstinner/bytecode
  description: bytecode is a Python module to generate and modify bytecode.
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A Python module to generate and modify Python bytecode.
  doc_url: https://bytecode.readthedocs.io/
  dev_url: https://github.com/vstinner/bytecode

extra:
  recipe-maintainers:
    - MatthieuDartiailh
