{% set name = "bytecode" %}
{% set version = "0.18.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d9564f1565fe1ae6a1173e544ef43a85f093e83997ef45af65d0d250eb48d7a1

build:
  skip: true  # [py<311]
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps . -vv --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools >=61.2
    - wheel
    - setuptools-scm >=3.4.3
    - toml
  run:
    - python

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
  imports:
    - bytecode
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest tests -v

about:
  home: https://github.com/MatthieuDartiailh/bytecode
  description: bytecode is a Python module to generate and modify bytecode.
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A Python module to generate and modify Python bytecode.
  doc_url: https://bytecode.readthedocs.io
  dev_url: https://github.com/MatthieuDartiailh/bytecode

extra:
  recipe-maintainers:
    - MatthieuDartiailh
