{% set name = "bytecode" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0c37efa5bd158b1b873f530cceea2c645611d55bd2dc2a4758b09f185749b6fd

build:
  skip: true  # [py<39]
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps . -vv --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools >=61.2
    - wheel
    - setuptools-scm >=3.4.3
    - toml
  run:
    - python
    - typing_extensions  # [py<310]

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
  imports:
    - bytecode
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest tests -v

about:
  home: https://github.com/MatthieuDartiailh/bytecode
  description: bytecode is a Python module to generate and modify bytecode.
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A Python module to generate and modify Python bytecode.
  doc_url: https://bytecode.readthedocs.io
  dev_url: https://github.com/MatthieuDartiailh/bytecode

extra:
  recipe-maintainers:
    - MatthieuDartiailh